version: 0.1
build:
    commands:
      - ant
#      - mkdir build-output
#      - cp -R dist/ build-output
#      - cd /build-output
#      - ll
post_build:
    commands:
      - echo Build completed
#      - mv build-output/* ./
artifacts:
  files:
    - dist/ant-web-application.war
    - appspec.yml
    - start_application.bash
    - stop_application.bash
  discard-paths: yes
