version: 0.1
phases:
    build:
        commands:
          - ant -Dant.build.javac.target=1.8 -Dant.build.javac.source=1.8
    post_build:
        commands:
          - echo Build completed
artifacts:
  files:
    - dist/ant-web-application.war
    - appspec.yml
    - start_application.bash
    - stop_application.bash
  discard-paths: yes
